version: '3'

networks:
  adonis5:
    external: true

volumes:
  postgres_data:

services:
  web:
    build: ./web
    image: tgl-web
    container_name: tgl-web
    ports:
      - '3000:3000'
    networks:
    - adonis5
    volumes:
    - ./web:/home/node/app/web
    
  api:
    build: ./server
    image: tgl-api
    container_name: tgl-api
    ports:
      - '3333:3333'
    volumes:
      - ./server/:/home/node/app/server
    networks:
      - adonis5
    depends_on:
      - redis
      - postgres

  migration:
    build: ./server
    # restart: always
    image: migration
    networks:
      - adonis5
    command: node ace migration:run
    depends_on:
      - postgres

  seeds:
    build: ./server
    image: seeds
    networks:
      - adonis5
    command: node ace db:seed
    depends_on:
      - migration
      - api

  scheduler:
    build: ./server
    image: scheduler
    networks:
      - adonis5
    command: node ace scheduler:run
    depends_on:
      - api

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tgl
    ports:
      - '5433:5432'
    networks:
      - adonis5

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - adonis5
